# Check that the code works
name: Check code

# Check links on the 2nd day of the month.
# 2nd as the first letter of this repo is the 2nd letter in the alphabet.
on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"


jobs:
  check-code:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
            install.packages("remotes")
            remotes::install_cran("testthat")
            remotes::install_cran("readr")
            remotes::install_cran("stringr")
            remotes::install_cran("ggplot2")
            remotes::install_cran("dplyr")
            remotes::install_cran("svglite")
        shell: Rscript {0}

      - name: Remove all figures
        run: rm *.png

      - name: Run code
        run: Rscript fig2_complete.R

      - name: Show all reproduced figures
        run: ls *.png
